じゃんけんで勝負する回数を入力する機能を追加
kai-takuto/zyanken pull request #3
Opened 2024-07-10 05:13 UTC by kai-takuto

ー内容ー
・じゃんけんで勝負する回数を入力する機能を追加
　・inputを使ってじゃんけんで勝負する回数を入力する機能を追加しました。

ー確認手順書ー
・プログラムを実行すると、文字を入力することができる。

2024-07-10 07:54 UTC, sugawarayss requested changes
コメントしましたー

2024-07-10 07:54 UTC, sugawarayss commented on zyanken.py
> +        n = int(input('じゃんけんしたい回数を入力してね\n--->'))
type annotationを付けましょう。
```suggestion
        n: int = int(input('じゃんけんしたい回数を入力してね\n--->'))
```

また、integer以外は排除できますが、0以下を入力した場合はどうしますか?

2024-07-10 07:54 UTC, sugawarayss commented on zyanken.py
> +    print('数字を入力してください↓↓↓↓↓↓')
おそらく↓のようになると思いますがこれで良いですか?
```shell
じゃんけんしたい回数を入力してね
--->3
数字を入力してください↓↓↓↓↓↓
```

2024-07-10 07:54 UTC, sugawarayss commented on zyanken.py
> +        pass
ユーザが入力した値が正しいのか?誤っているのか? が伝わらないと思います。
いじわるな考え方をすると、
漢数字や 全角数字、アラビア語の数字を入力している場合、永遠に
```shell
じゃんけんしたい回数を入力してね
--->
```
が表示され続けませんかね??? ユーザとしては回数を入力しているじゃん! ってなりませんか?

2024-07-11 01:32 UTC, kai-takuto commented on zyanken.py
> +    print('数字を入力してください↓↓↓↓↓↓')
Revをしていただきありがとうございます。

2024-07-11 01:49 UTC, kai-takuto commented on zyanken.py
> +        n = int(input('じゃんけんしたい回数を入力してね\n--->'))
Revをしていただきありがとうございます。
type annotationを付けました。
０以下の入力をした際に、エラーを起こしてValue Errorの処理を行うように変更しました。

2024-07-11 01:49 UTC, kai-takuto commented on zyanken.py
> +    print('数字を入力してください↓↓↓↓↓↓')
Revをしていただきありがとうございます。
VScodeとターミナル上で実行して見たところ、３を入力したら「じゃんけんしたい回数を入力してね--->3」のみ表示されて、「数字を入力してください↓↓↓↓↓↓」の表示は出ないので問題はないと思います。

2024-07-11 01:49 UTC, kai-takuto commented on zyanken.py
> +        pass
Revをしてくださりありがとうございます。
そのような視点で、考えていませんでした。
なのでエラーを起こした後に、
「print('自然数(1, 2, 3...)を入力してください↓↓↓↓↓↓' )」を表示するように変更しました。

2024-07-11 03:18 UTC, sugawarayss requested changes
コメントしました

2024-07-11 03:18 UTC, sugawarayss commented on zyanken.py
> +            raise ValueError
エラー内容を付けないとなぜエラーが発生したのかが伝わらないです。

2024-07-11 03:18 UTC, sugawarayss commented on zyanken.py
> +    print('自然数(1, 2, 3...)を入力してください↓↓↓↓↓↓')
ここの処理に到達する条件が読み取りづらいので変えましょう。

2024-07-11 03:18 UTC, sugawarayss commented on zyanken.py
> +print('{:-^4}'.format('-じゃんけんゲームが始まるぞ！！-\n'))
```python
print("-じゃんけんゲームが始まるぞ！！-\n") 
```
と書いていない理由はなぜですか?(同じことができるのにわざと複雑に書く必要はないと思います。)

2024-07-11 03:18 UTC, sugawarayss commented on zyanken.py
> +print('{:^30}'.format('入力した数だけじゃんけんできるぞ！！\n↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓\n'))
ここも↑と同じで、わざと複雑に書くメリットがないと思います。

あと、なぜここだけ2行の標準出力を1つの文字列でやっているんでしょうか? 
もしそうするなら1行目も同様にするなら多少納得できます。

2024-07-11 05:04 UTC, kai-takuto commented on zyanken.py
> +            raise ValueError
Revをしてくださりありがとうございます。
承知しました。
入力した値が自然数ではなかった場合に、「＊＊エラー：入力した値は自然数ではありません＊＊」とエラー内容を表示するように変更しました。

2024-07-11 05:05 UTC, kai-takuto commented on zyanken.py
> +print('{:-^4}'.format('-じゃんけんゲームが始まるぞ！！-\n'))
Revをしてくださりありがとうございます。
中央に寄せたいなと思った時に、formatを使った方法が記憶にあったので、こちらを使用しました。
菅原さんのおっしゃる通り、printでも同じことができるので、変更いたしました。

2024-07-11 05:07 UTC, kai-takuto commented on zyanken.py
> +print('{:^30}'.format('入力した数だけじゃんけんできるぞ！！\n↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓\n'))
Revをしてくださりありがとうございます。
・ここも↑と同じで、わざと複雑に書くメリットがないと思います。
→承知しました。
・あと、なぜここだけ2行の標準出力を1つの文字列でやっているんでしょうか?
もしそうするなら1行目も同様にするなら多少納得できます。
→特に意味はないまま、２行を１つの文字列で表示させていました。
　１行＝１つの文字列に統一しようと考え、変更いたしました。

2024-07-11 06:50 UTC, kai-takuto commented on zyanken.py
> +    print('自然数(1, 2, 3...)を入力してください↓↓↓↓↓↓')
Revをしてくださりありがとうございます。
if文を使ってn <= 0　をn > 0に変更して、breakするようにし、else: raise ValueErrorでエラー文に飛ばすように変更しました。

2024-07-11 07:06 UTC, sugawarayss requested changes
コメントしましたー

2024-07-11 07:06 UTC, sugawarayss commented on zyanken.py
> +    print('自然数(1, 2, 3...)を入力してください↓↓↓↓↓↓')
言い方が悪かったかな。。。
そうそうことではないですー。

せっかくtry-except を使っているのに、その外に処理があるから、どの場合にここが実行されるのかがわかりずらいので、メッセージを出すところを移動してほしいという意味でした。

ここで時間かかりすぎなので、答えですが、
except内にここの2つのprint()呼び出しを移動してください。

2024-07-11 07:06 UTC, sugawarayss commented on zyanken.py
> +            raise ValueError
普通は Exceptionクラスだけでraiseはしないです。
以下のようにエラーの概要を文字列で渡して使います。
```suggestion
            raise ValueError("input value is not valid integer. it must be number that larger than 0")
```

2024-07-11 07:13 UTC, kai-takuto commented on zyanken.py
> +            raise ValueError
承知しました。
ご指摘してくださった２箇所を、変更いたしました

2024-07-11 07:51 UTC, sugawarayss requested changes

2024-07-11 07:51 UTC, sugawarayss commented on zyanken.py
> +        pass
ここ動作確認しましたか?

2024-07-11 08:20 UTC, kai-takuto commented on zyanken.py
> +        pass
申し訳ありません。
そのまま追加してプッシュしてしまいました。
「except ValueError as e:
print(e)」を追加してエラー文の表示確認できました。

2024-07-11 08:26 UTC, sugawarayss commented on zyanken.py
> +        pass
`pass` は pythonにおいて `処理なし(何もしない)` という意味です。
print を except のスコープに移動したなら `pass` はけしてください

2024-07-11 08:28 UTC, kai-takuto commented on zyanken.py
> +        pass
承知いたしました。

2024-07-11 08:30 UTC, sugawarayss approved these changes
LGTM

2024-07-11 08:38 UTC, merged