じゃんけんの勝敗を比較する部分を追加
kai-takuto/zyanken pull request #4
Opened 2024-07-11 09:56 UTC by kai-takuto

ー内容ー
・(グー：１,チョキ：２,パー：３)の1~3を入力させることを前提として、自分とcpuの出し手を比較して勝敗を決める部分を追加
・比較した後の結果を格納するresult ={'win': 0, 'lose': 0, 'draw': 0}を追加
ー確認手順書ー
・your_handsが自分の出し手で、cpu_handsがcpuの出し手です。
・関数は返り値のresultを返して、{'win': 0, 'lose': 0, 'draw': 0}の中に格納していきます。
ー工程手順ー
1.じゃんけんで勝負する回数を入力するようにする。
2.出し手の勝敗を比較する仕組みを作る。　　　　　　　(現在地)
3.じゃんけんで出す手を入力するようにして、入力した回数ループさせるようにする。
4.指定回数の対戦を終了したら、総合成績を表示させるようにする。

ー次の工程ー
・じゃんけんで出す手を入力するようにして、入力した回数ループさせるようにする。

2024-07-12 01:12 UTC, sugawarayss requested changes
コメントしましたー

2024-07-12 01:12 UTC, sugawarayss commented on zyanken.py
> +def zyanken(your_hands, cpu_hands, result):
- 引数と戻り値の型ヒントを付けてください。(調べましょう)
- 総合結果を引き回すのはスマートじゃないですね。関数`zyanken` と `総合結果` は直接は関係していないので分離したほうが良いと思います。

2024-07-12 01:12 UTC, sugawarayss commented on zyanken.py
> +result ={'win': 0, 'lose': 0, 'draw': 0}
- 代入演算子はスペースで区切ってください。
- 変数に型ヒントを付けてください

2024-07-12 01:12 UTC, sugawarayss commented on zyanken.py
> +    if your_hands == cpu_hands:
[Question]
このスクリプトで想定しているPythonのバージョンは何でしょうか?

2024-07-12 02:55 UTC, kai-takuto commented on zyanken.py
> +    if your_hands == cpu_hands:
python 3.12.4ではないのでしょうか。

2024-07-12 03:10 UTC, sugawarayss commented on zyanken.py
> +    if your_hands == cpu_hands:
私は知りません。
どのversion使って開発してますか?
python(に限らないですが) はversionによって新しい記述方法が増えたり減ったりします。
それによって最適な書き方が変わります。

2024-07-16 02:03 UTC, kai-takuto commented on zyanken.py
> +    if your_hands == cpu_hands:
私が使用しているバージョンは3.12になります。
承知しました。

2024-07-16 02:03 UTC, kai-takuto commented on zyanken.py
> +result ={'win': 0, 'lose': 0, 'draw': 0}
承知しました。
変更いたしました。

2024-07-16 02:11 UTC, kai-takuto commented on zyanken.py
> +def zyanken(your_hands, cpu_hands, result):
承知しました。
関数zyankenの部分でwin・lose・drawの結果を返して、その結果をcount関数を使用して記録できるようにして、その記録をリストの中に格納するように変更しました。実行してみたところ、結果表示できていました。

2024-07-16 02:59 UTC, sugawarayss requested changes
コメントしました

2024-07-16 02:59 UTC, sugawarayss commented on zyanken.py
> +    print_results = []
実装作業中ならば、ここにずらずら処理を書いても良いですが
基本的にはmain()を呼ぶ程度の最低限にしてください。

デバッグ用や開発時の一時的な処理は残すべきではないです。

2024-07-16 02:59 UTC, sugawarayss commented on zyanken.py
> +    if your_hands == cpu_hands:
> 3.12

[Question]
なるほど、ならばここの処理は他にどんな処理方法が考えられますか?
考えられる場合はこの処理方法を選んだ理由は何ですか?

2024-07-16 03:54 UTC, kai-takuto commented on zyanken.py
> +    print_results = []
承知しました。

2024-07-16 04:04 UTC, kai-takuto commented on zyanken.py
> +    if your_hands == cpu_hands:
他の処理方法は思いつきませんでした。

2024-07-16 04:35 UTC, sugawarayss requested changes

2024-07-16 04:35 UTC, sugawarayss commented on zyanken.py
> +    if your_hands == cpu_hands:
勝敗のメッセージと勝敗の判定は`別の役割`です。
また各分岐でやっていることがほぼ同じなので共通化 & 分離しましょう。

共通化する時のヒント:
`勝ち`でないということは`負け`です。

メッセージ分離する時のヒント:
こういう時にformat文字列を使います。

2024-07-16 04:35 UTC, sugawarayss commented on zyanken.py
> +        print('＊＊エラー：1~3の数字を入力してください＊＊')
elseの時に何も返却していないです。
万が一、この分岐に入るとどうなりますか

2024-07-16 04:51 UTC, sugawarayss requested changes
追加コメントしましたー

2024-07-16 04:51 UTC, sugawarayss commented on zyanken.py
> +    wins = results.count('win')
型ヒント付けましょう

2024-07-16 08:51 UTC, kai-takuto commented on zyanken.py
> +    if your_hands == cpu_hands:
承知しました。
共通化が終わりました。

2024-07-16 08:55 UTC, kai-takuto commented on zyanken.py
> +        print('＊＊エラー：1~3の数字を入力してください＊＊')
elseの部分に入ったら、Noneが戻ってprintの部分が表示されると思います。

2024-07-16 09:09 UTC, kai-takuto commented on zyanken.py
> +    wins = results.count('win')
承知しました。
list ->Noneに変更しました。

2024-07-16 09:16 UTC, sugawarayss commented on zyanken.py
> +    wins = results.count('win')
戻り値もそうですが、winsやlose等の変数にも付けましょう

2024-07-16 09:19 UTC, sugawarayss commented on zyanken.py
> +        print('＊＊エラー：1~3の数字を入力してください＊＊')
言葉足らずでしたね。。。

> Noneが戻ってprintの部分が表示される
そうですが、関数の型ヒントと矛盾するということが言いたかったことでした。
ヒントでは 戻り値は str といっているのに None が返るのが矛盾してました。

変更でその部分は無くなったので変更は不要です

2024-07-16 09:34 UTC, kai-takuto commented on zyanken.py
> +    wins = results.count('win')
承知しました。
winsやloseなどの変数に型ヒントを追加しました。
戻り値にも付与というのは、'win'・'lose'・'draw'の部分のこを指していますでしょうか。

2024-07-17 01:41 UTC, sugawarayss approved these changes

2024-07-17 01:44 UTC, merged